version: '3.9'
services:
  frontend:
    container_name: ngcash_frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: ngcash_backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: npm run dev
    volumes: 
      - ./backend/src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - JWT_SECRET=jwt_secret
      - PGUSER=postgres
      - POSTGRES_PASSWORD=123456
      - PGHOST=db
      - PGPORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: postgres
    container_name: ngcash_db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=NG_CASH
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "NG_CASH"]
      timeout: 60s
      retries: 5
    restart: 'always'
    cap_add:
      - SYS_NICE